### ISSUE TITLE
Refresh timeline 

### ISSUE THREAD

**Issue by urossavelj** [ramarao9/AttachmentUploader#13]
I don't see the Timeline in the list, when selecting a ControlNameForRefresh, so I can't select it.

**Comment by ramarao9** [comment]
@urossavelj Which entity are you using and can you verify if Notes is enabled for that entity?

**Comment by urossavelj** [comment]
@ramarao9 it's a custom entity, is this the problem?

Notes are also enabled as the control by itself works OK, it just doesn't refresh the timeline as you can't select it.

**Comment by urossavelj** [comment]
I realized that you can manually enter the control name instead of using the drop down menu. That way it works.

**Comment by ramarao9** [comment]
@urossavelj Correct, that's the way it will work as it only supports text entry instead of dropdown. Closing the issue for now, feel free to reopen if you face issues.
