### ISSUE TITLE
mimetype not being set

### ISSUE THREAD

**Issue by leibishr** [ramarao9/AttachmentUploader#2]
Hi ramarao9,

Thank you very much for this custom control. it is really helpful and useful.
While using the AttachmentUploader I noticed one small issue, it doesn't set the "mimetype" when creating the annotation record.

Is this something that can be worked on?

Thank You!
Leibish Ringel

**Comment by ramarao9** [comment]
Hi Leibish,

Thanks for using the control! I will look at the issue and add a fix to this. 

Thanks, 
Rama Rao

**Comment by ramarao9** [comment]
I have applied the fix for the Mime Type, could you give it a try?
