### ISSUE TITLE
PCF control spins forever and doesn't load on Opportunity entity #2

### ISSUE THREAD

**Issue by jogendarb** [ramarao9/AttachmentUploader#23]
I'm trying to use this on Opportunity Entity, followed the steps listed on the github page.

![image](https://user-images.githubusercontent.com/22617839/131170142-9b6de0ae-2ba5-4891-9592-b19b0f6baeda.png)

![image](https://user-images.githubusercontent.com/22617839/131170204-41b63609-7f12-47d6-bf82-d1bcc2b8daab.png)

![image](https://user-images.githubusercontent.com/22617839/131170237-195c3a21-9841-4997-865c-4bffdb2b1004.png)

The form doesnt have custom javascripts on it

**Comment by ramarao9** [comment]
@jogendarb Could you provide the following

- Browser
- Org Version
- AttachmentDragandDrop Solution type and version
- Screenshot of any errors in the console. 
   - Open Developer tools by pressing F12 or Ctrl+Shift+I
   - Navigate to console and change filter to Errors only as below
      
![image](https://user-images.githubusercontent.com/37280856/131346753-aca60691-8f42-4651-941c-127fb5ba8823.png)


Also, just to make sure, can you double click the Notes control on the form and verify if the Unique Name is 'Timeline'?
Does it work on a different entity or form?

**Comment by jogendarb** [comment]
Thank you for your reply. Please find the requested details below:
- Browser - Chrome(normal/Incognito) and Edge
- Org Version - Version 1710 (9.2.21074.132) online
-  AttachmentDragandDrop Solution
![image](https://user-images.githubusercontent.com/22617839/131357393-a8d80f49-2246-4e80-9c39-156489bb5fb1.png)
- Screenshot of console
![image](https://user-images.githubusercontent.com/22617839/131356296-da41cbfb-5027-43e8-8e54-b927743e1ea8.png)
- Notes control unique name is Timeline
- I tried on Account form and it is spinning there as well.

**Comment by ramarao9** [comment]
Thank you for the details. All the configuration looks good, I also tested it on the same version and it will work. Can you try couple of additional steps

- Uninstall the solution and reinstall it. See if there is any difference
- In Chrome, can you take a look at the console without any filtering(remove Errors only filter) to see anything that would show messages for AttachmentUploader.tsx or index.ts ?
- A little bit more technical, but if you can try the below steps that would be great:
   - Go to Sources tab and hit Ctrl+P. Select the index file associated to AttachmentUploader
![image](https://user-images.githubusercontent.com/37280856/131503434-f5a04581-9394-4426-89e4-4c842dad1cf6.png)
    - Put a breakpoint as shown below. Refresh the form and see if it reaches this step. This will tell us if the control is even being initialized.
    
![image](https://user-images.githubusercontent.com/37280856/131503598-856f2a4b-6098-4674-b6de-9143fb85e59f.png)

**Comment by jogendarb** [comment]
I uninstalled and installed the solution, didnt make a difference. I tried debugging and the execution went till the below break point and I dont see anything related to the control in console.
![image](https://user-images.githubusercontent.com/22617839/131515925-60407794-d8ab-4387-be57-100a64ca50f4.png)

**Comment by ramarao9** [comment]
Seems like it's getting the id of the record and when it tries to render the html that's when it doesn't do anything. As a quick test, can you see if you are able to add any other PCF controls without issues?

On the AttachmentUploader.tsx file, can you see if any of the below breakpoints are being hit?

![image](https://user-images.githubusercontent.com/37280856/131669959-bf349fe6-0d8f-41ab-ac00-60863690d125.png)


![image](https://user-images.githubusercontent.com/37280856/131670013-039c8554-1868-4ba4-8453-e6b0fe55416a.png)

**Comment by jogendarb** [comment]
All those break points were being hit without issues:
![image](https://user-images.githubusercontent.com/22617839/131723949-ce21cd03-6db6-46db-8cb3-47f0720bbf59.png)

**Comment by ramarao9** [comment]
If all the breakpoints are hitting, I'm not sure why it's not rendering. Are you able to add any other PCF components on the form either OOB or from pcf.gallery?

**Comment by jogendarb** [comment]
Issue was resolved after I created a new field and attached the PCF control to it.

**Comment by jogendarb** [comment]
Thank you very much for all your support in debugging the issue
