### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hsoBHussain** [ramarao9/AttachmentUploader#24]
When trying to upload a a big file (more than 4-5 MB) there is an error of Maximum call stack size exceeded. It works fine for first couple of time and after that the error keeps on popping. If you clear the browser cache the control starts working fine again and then after 1-2 attempts stops
![MaximumCallStackError](https://user-images.githubusercontent.com/96235357/151173583-d70fbad5-2322-4221-8ef1-ac16ed8e4c3c.PNG)
.

**Comment by ramarao9** [comment]
Hi @hsoBHussain, can you click Show Details, there should be able to download the log file at the bottom. Can you send it over?

**Comment by hsoBHussain** [comment]
Hi @ramarao9 thank you for your prompt reply on it. There is no log file when I click show details button. I only get the following information

```
Error code: 0x0
Session Id: 99157f21-95a0-4b0b-9d0a-38f6aa3f6d3e
Activity Id: e23f94d3-bb7e-4deb-8804-c4e4cdb6295c
Time: Wed Jan 26 2022 15:03:46 GMT+0100 (Central European Standard Time)
```

**Comment by ramarao9** [comment]
Interesting, can you open the developer tools(F12 or Ctrl+Shift+I) and go to the Network tab. Clear out any existing requests and try uploading again. When the issues happens, there should be a failed request with status of 500. If you can send me the response, that would be great.

![image](https://user-images.githubusercontent.com/37280856/151178709-49c00e14-2200-4f4e-a81f-1e8878982be9.png)

**Comment by hsoBHussain** [comment]
I already checked that but there are no Failed requests. All of them are with status 200.

**Comment by ramarao9** [comment]
Could be related to an issue in the control's UI rendering in a certain situation. Can you see if there is a trace of the error in the console? This might help identify what could be causing it.

![image](https://user-images.githubusercontent.com/37280856/151279994-0805577c-a423-4168-a1fc-fdefdf8cfa02.png)

**Comment by hsoBHussain** [comment]
@ramarao9 surprisingly there are no errors in the console related to this error I think. Please see the screenshot attached
![image](https://user-images.githubusercontent.com/96235357/151778099-381a2cdf-9985-4fde-a429-81fd62fb5e15.png)

**Comment by ffermi** [comment]
This might help:
![image](https://user-images.githubusercontent.com/7914684/155324909-f95cfcd8-4726-487f-9ae4-cc6b0c3a3f0f.png)

**Comment by ramarao9** [comment]
Thank you and sorry for the delay. Will look at it either today or tomorrow and let you know what I find.

**Comment by ramarao9** [comment]
@hsoBHussain A new release has been added that resolves this issue.  Let me know if you are still experiencing any issues with the new solution.
