### ISSUE TITLE
Timeline Does not refresh automatically after uploading file

### ISSUE THREAD

**Issue by Megancs** [ramarao9/AttachmentUploader#38]
Hello Rama, 

Thank you for creating this tool. 

I am able to uploade files to timeline, but unfortunatly the timeline doesn't refrash automatically. So the file is not visible in the timeline as soon as you upload it. The user has to refresh the page to be able to see the file in the timeline. Here is a screenshot of the configuration. Can you please tell me if there is something I am missing? 

![Screenshot 2024-02-22 095940](https://github.com/ramarao9/AttachmentUploader/assets/160839190/d3c11beb-3713-4c3f-a700-bcbb13a2791e)

Thanks!!
Megan

**Comment by ramarao9** [comment]
Hi Megan,

What's the version of the solution you are using and, are you using this on a Custom table or OOB table? If OOB table, can you provide the name?

**Comment by Megancs** [comment]
Hi Rama,

Thanks for the quick respons. I just downloaded the managed solution two
days ago, so it’s version 1.0.1.0
[image: image.png]
I am using an OOB Field Service table, Work Order - schema
name: msdyn_workorder

I would like to state that it is my first time working with PCF. I followed
these steps.
- downloaded the managed solution
- imported it to the environment
- navigated to the work order form I want to use
- configured the PCF as shown on the previous screen shot

Thanks again, I’m looking forward to your response.

tors. 22. feb. 2024 kl. 23.06 skrev Rama Rao Koneru <
***@***.***>:

**Comment by Megancs** [comment]
Hello Rama, 

I have resolved the issue now. Thank you for taking your time to repond though! 
Thank!

**Comment by ramarao9** [comment]
@Megancs Glad you were able to resolve the issue. What was the resolution?

**Comment by Megancs** [comment]
@ramarao9 I didn't realize that my client had 2 timelines on the workorder form. It was under a different tab. Once I removed the 2nd timeline it refreshed automatically after uploading a file. So the issue was caused due to multiple timelines on the form. 
Sorry for the inconvenience!

**Comment by ramarao9** [comment]
@Megancs No problem, that is hard to find
