### ISSUE TITLE
Not working on Opportunity timeline

### ISSUE THREAD

**Issue by m-oscarsson** [ramarao9/AttachmentUploader#5]
When trying to drag-and-drop on an opportunity timeline it gives an error that the entity Opportunitys cannot be found. The plural name is Opportunities by english standard.

Guess this line is the culprit :)

AttachmentUpload/AttachmentUploader.tsx line 51:
attachmentRecord[`objectid_${entity}@odata.bind`] = `/${entity}**s**(${id})`;

The error exists in AttachmentDragandDrop_1_0_0_2_Managed.zip

**Comment by ramarao9** [comment]
Hi @m-oscarsson,  that seems like the issue :)  I will add a fix to dynamically retrieve this value. Should have a fix in 1-2 days.

**Comment by m-oscarsson** [comment]
Thank you for your response and for your PFC!

Best regards,
Mark

Den mån 4 maj 2020 kl 16:56 skrev Rama Rao Koneru <notifications@github.com

**Comment by ramarao9** [comment]
Thank you! I added the fix in the latest release. Could you give that a try?

**Comment by m-oscarsson** [comment]
Works great!
