### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Mattw112** [ramarao9/AttachmentUploader#9]
Hi I am trying to follow the instructions but must be doing something incorrect?

I imported your unmanaged solution and published everything
I opened my form
I created a section, single column.
I created a field called MSAAttachment that is a single line of text with 255 characters
I added this field to the column
I opened the properties and added AttachmentUpload control and made default for all three types (phone, Web, Tablet)
I set the ControlNameForRefresh to my field MSAAttachment (Your instructions say name of the grid??  How do I add a grid for this, what do I tied it's datasource to?)
I checked "Hide Default Control"
I Set the field to not show label

I saved everything and published it.  But I just get an error "Error Loading the Control"

Can you tell me where I'm doing something wrong?

THanks,
Terry

**Comment by ramarao9** [comment]
Hi Terry,

Does your entity have Notes enabled and you can save attachments on it or is it the Email entity?

The ControlNameToRefresh would be the grid that shows the attachments. Typically has the below two values unless they have been modified on the form
      
- attachmentsGrid: when the entity is Email. 
- Timeline: when the entity is not Email and the entity has notes enabled to associate the attachments. This is inside the Social Pane tab.

**Comment by Mattw112** [comment]
Hi thanks for responding.  Ye sit is notes enabled, but I didn't have a timeline control on the form.  I didn't realize this just added to the timeline.  I added a timeline control and everything works now.  Thanks.

**Comment by ramarao9** [comment]
Glad that fixed the issue.
